[Room]
TitleFontName=Arial
TitleFontSize=22
TitleFontColor=clGreen
TitleFontPositionTop=5
TitleFontPositionLeft=345
TitleFontStyle=[fsBold]
RoomFontName=Arial
RoomFontSize=16
RoomFontColor=clGreen
RoomFontPositionTop=10
RoomFontPositionLeft=20
RoomFontStyle=[]
HandTop=9
HandLeft=810
KarelShape=karel.3ds
#KarelTexture=karel.jpg
KarelTexture=none
KarelPosX=0
KarelPosY=0,73
KarelPosZ=0
KarelScaleX=1
KarelScaleY=1
KarelScaleZ=1
Rounded=1
RoundX=70
RoundY=70


[Navigator]
TitleFontName=Arial
TitleFontSize=10
TitleFontColor=clGreen
TitleFontPositionTop=3
TitleFontPositionLeft=12
TitleFontStyle=[]
HandTop=3
HandLeft=106
LineWidth=1
Rounded=1
RoundX=30
RoundY=30

[Command]
TitleFontName=Arial
TitleFontSize=10
TitleFontPositionTop=3
TitleFontPositionLeft=12
TitleFontStyle=[]
HandTop=3
HandLeft=106
LineWidth=1
Rounded=1
RoundX=30
RoundY=30

[Editor]
TitleFontName=Arial
TitleFontSize=22
TitleFontColor=clGreen
TitleFontPositionTop=2
TitleFontPositionLeft=12
TitleFontStyle=[fsBold]
HandTop=7
HandLeft=106
LineWidth=2
TitleColor=clBlack
ProgramColor=clGreen
Rounded=1
RoundX=70
RoundY=70
